- src/handlers/createOrg.js
- src/handlers/login.js
- src/handlers/register.js
Sometimes you try to log in and it takes a while. In that time, the challenge expires so I have extended the life time of the challenge to 15mins
> make the challenge last for 15 mins

- src/frontend/AuthProvider.jsx
- src/handlers/handleAuth.js
- src/handlers/me.js
- src/handlers/setup.js
Includes helpers for
* Orgs
* Claims
* Feature Flags
* Permissions
> Add permission and feature flag helpers to frontend

- src/authMiddleware/authMiddleware.js
Include post login redirects to middleware
> Redirects in middleware

- src/handlers/pageRouter/createOrg.js
Fixes issue where orgs weren't being created on pages router
> Create org with pages router

- src/session/appRouter/getFlag.js
- src/session/pagesRouter/getFlag.js
> fix: get feature flags

- package.json
Updated `package.json` version.
> updated package.json version  to fix failed release

- src/frontend/AuthProvider.jsx
- src/session/appRouter/getFlag.js
- src/session/pagesRouter/getFlag.js
Get Flag errors out when default value is `false`, so I fixed it.
Now it wont error out
> fix: default value default

- package-lock.json
- package.json
Move `release-it` dependency to a dev dependency
> fix: release-it to dev Dep

- src/handlers/pageRouter/setup.js
set header to no-cache -> on setup no longer finds phantom user
> fix: no longer have phantom user after logging out

- src/session/appRouter/getUserOrganizations.js
> Return orgCodes as expected from helper

- src/handlers/appRouter/callback.js
- src/handlers/appRouter/logout.js
- src/handlers/pageRouter/callback.js
- src/handlers/pageRouter/logout.js
Allow cookies to be set on safari
> bug: configure samesite and lax to work on safari

- index.d.ts
- src/handlers/pageRouter/callback.js
- src/index.js
- src/utils/pageRouter/isTokenValid.js
Add `isTokenValid` helper which can be called from pages router middleware
> isTokenValid helper for pages router

- src/handlers/pageRouter/callback.js
- src/utils/pageRouter/isTokenValid.js
> Token payload

- src/handlers/appRouter/callback.js
- src/utils/pageRouter/isTokenValid.js
> Aud checking was using === instead of ==

- readme.md
Update README with starter kit link
Fixes: #62 
> Update README with starter kit link

- src/components/LoginLink.js
- src/components/RegisterLink.js
Fix strict equals check on Org code
> fix: strict equals

- package-lock.json
- package.json
> chore: next-14 peer dep

- package.json
- revert version so hopefully releasing works
> chore: revert version

- package-lock.json
- package.json
- src/session/sessionManager.js
> Fix cookie on edge

- src/config/index.js
- src/session/sessionManager.js
- allow users to set the domain at which their tokens are set
> feat: cookie domain

- package-lock.json
- package.json
> chore: bump TS dependency

- src/handlers/setup.js
> fix: setup

- src/session/sessionManager.js
- fix removal of cookies when cookie domain is set
> fix: removing cookies across domains

- src/session/sessionManager.js
- remove cookies from root domain
> fix: remove cookies from root domain

- src/authMiddleware/authMiddleware.js
- can configure middleware to return to current page or use default redirect url
> feat: middleware to return to current page

- package-lock.json
Patch to resolve dependancies security issues
> deps: security update socks 2.7.1 > 2.7.3

- src/handlers/auth.js
- src/handlers/health.js
This adds a health check, it output in json format the Kinde configuration.
This will assist in diagnosing issues especially when pushed to production around configuration
Secret checks the format, if detects a secret that parses the right format will show `Set correctly`, otherwise will show `Not set correctly`
> feat: health check endpoint

- src/session/sessionManager.js
- src/utils/appRouter/setVerifierCookie.js
- src/utils/pageRouter/setVerifierCookie.js
This makes the cookie list more DRY
Also enforces `sameSite`, `httpOnly` and `secure` options on all cookies.
> fix: Cookie settings and code clean

- package.json
> fix: types export

- src/handlers/setup.js
- in case of undefined orgNames
> fix: setup map undefined

- src/session/index.js
Fix issue with missing config 
Fixed:https://github.com/kinde-oss/kinde-auth-nextjs/issues/161
> fix: session index error with missing config

- src/session/index.js
> fix: correct import path

- src/authMiddleware/authMiddleware.js
- add redirectURLBase to options in middleware
> feat: add redirectURLBase to options

- package.json
> chore: update TS SDK version

- src/components/LoginLink.js
null check was failing, this is a quick fix
> fix: failing null check

- src/handlers/pageRouter/logout.js
- clear cookie domain cookies in pages router
> fix: logout clear cookie domain

- src/handlers/callback.js
Fixes the `isReturnToCurrentPage` option on `withAuth`.
Fixes: https://github.com/kinde-oss/kinde-auth-nextjs/issues/188
> fix: isReturnToCurrentPage

- src/config/index.js
- src/routerClients/AppRouterClient.js
- src/routerClients/PagesRouterClient.js
This updates the framework analytic to distinguish between pages and app router
> chore: update framework tracking

- src/handlers/callback.js
- src/session/getUser.js
- change console.error to warn for getUser and isAuthenticated
> chore: warn getuser

- src/handlers/callback.ts
- js to ts
- include helpful error message
> chore: fix callback error

- package-lock.json
- package.json
- pnpm-lock.yaml
Update `cookie` to version 1.0.0 and run `npm audit fix`
> chore: update cookie library

- clientConfig/rollup.config.js
- middlewareConfig/rollup.config.js
- package-lock.json
- package.json
- serverConfig/rollup.config.js
- src/authMiddleware/authMiddleware.ts
- src/handlers/setup.ts
- src/session/getAccessToken.js
- src/session/getIdToken.js
- src/session/getUser.ts
- src/session/getUserOrganizations.ts
- src/session/isAuthenticated.js
- src/utils/pageRouter/isTokenValid.js
This replaces `jwt-decode` with `@kinde/jwt-decoder`
Added token validation check to the isAuthenticated method
Added token validation check to the authMiddleware 
> fix: validate token on isAuthenticated

- src/session/sessionManager.js
- remove console error that is noisy during next14 build
resolves: https://github.com/kinde-oss/kinde-auth-nextjs/issues/231
> fix: remove noisy error log

- playground/src/app/protect/page.tsx
- src/handlers/protect.js
Addressing issues in previous PR #154. 
1. fixed import error
2. in next js catching a redirect won't redirect so I removed try/catch statment
3. added  `postLoginRedirectURL` and `orgCode` options
4. (idk if this is a proper fix) called page function and not return jsx
5. added protect route to playground to demo functionality  
- [ x] I have read the [“Pull requests” section](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md#pull-requests) in the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md).
- [ x] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md).
🛟 _If you need help, consider asking for advice over in the [Kinde …
> fix: import error in protect file

- src/authMiddleware/authMiddleware.ts
- src/components/CreateOrgLink.js
- src/components/LoginLink.js
- src/components/LogoutLink.js
- src/components/RegisterLink.js
- src/config/index.ts
- src/frontend/AuthProvider.jsx
- src/frontend/KindeBrowserClient.ts
- src/handlers/auth.js
- src/handlers/protect.js
- src/utils/redirectOnExpiredToken.ts
This adds the ability to customise the API routes used by the SDK for auth functions.
> Custom API routes

- src/authMiddleware/authMiddleware.ts
- src/config/index.ts
- src/routerClients/AppRouterClient.js
- src/routerClients/PagesRouterClient.js
- src/utils/redirectOnExpiredToken.ts
The API route environment variable was not always respected
> fix: api route not always respected

- src/handlers/callback.ts
- src/handlers/createOrg.ts
- src/handlers/login.ts
- src/handlers/register.ts
- src/utils/validateState.ts
When the state is passed to the login, this PR stores the state, upon return it reads the state and passes it back to the site or post login redirect URL 
> feat: pass state back on auth completion

- src/session/getFlag.js
Fix getFlags not returning values correctly
Fixes: https://github.com/kinde-oss/kinde-auth-nextjs/issues/304
> fix: getFlag result

- src/authMiddleware/authMiddleware.ts
This change adds an `orgCode` parameter to the auth middleware options. Including this parameter will include the `org_code` URL parameter in any login redirects initiated by middleware. This solves for the use case where a customer wants to send all users to the login screen for a particular organization.
The `org_code` URL parameter is supported [when redirecting from the auth handlers](https://github.com/kinde-oss/kinde-auth-nextjs/blob/4a1bb931a42a29e243c60b67000386fee730f33d/src/utils/generateAuthUrl.js#L4) and similar functionality is already in use in the [LoginLink component](https://github.com/kinde-oss/kinde-auth-nextjs/blob/4a1bb931a42a29e243c60b67000386fee730f33d/src/components/LoginLink.js#L27)
🛟 _If you need help, consider asking for advice over in the [Kinde …
> feat: Add orgCode middleware option

- package.json
- pnpm-lock.yaml
- src/components/PortalLink.tsx
- src/components/index.js
- src/config/index.ts
- src/handlers/auth.js
- src/handlers/portal.ts
> feat: portalLink

- package.json
This updates type location, quick fix to resolve after previous update changed how types were generated
> fix: type declaration

- src/authMiddleware/authMiddleware.ts
When token was refreshed, it didn't honour the session persistence setting.
> fix: refresh cookies not using session cookies when non persist is set
