- index.d.ts
- server/index.d.ts
- src/components/CreateOrgLink.js
- src/components/LoginLink.js
- src/components/LogoutLink.js
- src/components/RegisterLink.js
- src/handlers/appRouter/register.js
- src/server/index.js
Add Server Side Components for Login / Register / Logout and CreateOrg links
> Add auth link components

- src/config/index.js
1. There was a typo in `KINDE_POST_LOGIN_URL_REDIRECT_URL` which had an extra `URL` updated the API of the SDK to allow both in the name of backwards compatability:
`KINDE_POST_LOGIN_URL_REDIRECT_URL`
or
`KINDE_POST_LOGIN_REDIRECT_URL`
2. Removed baked in vercel fallbacks
> fix: typo in post login url - allow both versions

- src/components/CreateOrgLink.js
- src/components/LoginLink.js
- src/components/LogoutLink.js
- src/components/RegisterLink.js
- src/config/index.js
- src/frontend/AuthProvider.jsx
I have added the ability to support custom API paths using the ENV var `KINDE_API_PATH`. This is important as it helps migrating from another library e.g. NextAuth. Both libraries use the same route `/api/auth` which means you can't run them side by side when migrating between the two and makes migrations more complex and risky.
> Allow custom API path

- src/components/LoginLink.js
- src/components/RegisterLink.js
- src/handlers/appRouter/callback.js
- src/handlers/appRouter/handleAuth.js
- src/handlers/appRouter/login.js
- src/handlers/appRouter/register.js
- src/utils/appRouter/prepareForRedirect.js
- src/utils/appRouter/setVerifierCookie.js
- enable devs to set a `post_login_redirect_url` query param in the app router to determine where a user is redirected after logging in.
- baked it into the LoginLink + RegisterLink too with prop `postLoginRedirectURL`
> post login redirect for app router

- package-lock.json
- package.json
- src/utils/randomString.js
- src/utils/sha256.js
I replaced the two usages of Node.js crypto with uncrypto as it is already used in the typescript sdk, which this package depends on. This should allow Next.js apps using Kinde to run on the Vercel Edge Runtime and other platforms which don't support Node.js APIs.
> Replace node:crypto with uncrypto

- src/authMiddleware/authMiddleware.js
- src/handlers/appRouter/callback.js
- src/handlers/pageRouter/callback.js
- src/utils/generateAuthUrl.js
- src/utils/generateCallbackUrl.js
Commonly finding people have `//` between their domains and paths when deploying to services like Vercel that seem to add a trailing slash at build time.
Added a function to create callback URLs which ensures there is always a single slash between domain and path
> Make sure always a single slash between domain and path in callbacks

- src/handlers/register.js
- register was taking end users to the login page -> now it should take them to the register page
> fix: register takes you to register page (not login)

- .gitignore
- package.json
- readme.md
Add playground to allow easier contributions
> feat: add playground

- package-lock.json
- package.json
Native atob function was not correctly decoding all unicode charaters, replaced with updated version of TS SDK which handles this
> fix: encoding of unicode characters

- src/utils/generateAuthUrl.js
This passes the login_hint down to the auth flow to allow pre-filling emails on the pages flow.  This is a 1.x fix
> add login hint to the auth urls

- src/routerClients/RouterClient.js
The class property definitions should happen at root level not inside the constructor.
> fix: move router type definitions

- src/session/getUserOrganizations.js
Fix which caused getUserOrganizations to return null
> fix: getUserOrganizations returning null incorrectly.

- src/authMiddleware/authMiddleware.js
Since the commit 817d1b3 that was uploaded a day ago, a **TypeError** appeared with a simple setup of a Nextjs project and this library, specifically, by using the _withAuth_ middleware which is used to protect routes.
The error was the following: 
By seeing the changes made, it seems the _redirectURLBase_ is indeed being read from an object that may be undefined; therefore, it only raises that error by using the middleware, at least, with a simple setup and use of _withAuth_ middleware. The variable ***option*** is not always passed to the ***handleMiddleware***, so that is why and where the error happens. 
While these changes can fix the issue, perhaps other features were trying to be implemented with the usage of the variable ***options***, so I'm not sure whether the variable …
> fix: add optional chainings to handleMiddleware function to avoid raising a TypeError

- src/handlers/callback.js
- src/handlers/createOrg.js
- src/handlers/login.js
- src/handlers/logout.js
- src/handlers/register.js
- src/routerClients/AppRouterClient.js
- use next response redirect instead of redirect from next/navigation
> fix: use NextResponse redirect

- src/components/LoginLink.js
When reletive URL is passed to the `postLoginRedirectURL` property of login, append the host.
Resolves: https://github.com/kinde-oss/kinde-auth-nextjs/issues/174
> fix: use host/environment variable if relative postLoginRedirectURL supplied

- src/handlers/auth.js
- src/handlers/callback.js
- src/routerClients/AppRouterClient.js
- src/routerClients/RouterClient.js
- `onError` callback function can be passed into `handleAuth` to handle errors when handling redirect back to app during auth flow (state check) - *app router only*
- better error handling around environment variables - an error is thrown in client secret, client id, site url or issuer url are missing from `.env`
- [ x ] I have read the [“Pull requests” section](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md#pull-requests) in the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md).
- [ x ] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md).
🛟 _If you need help, consider asking for advice over in the [Kinde …
> feat: on error callback fn

- src/handlers/auth.js
- src/handlers/callback.js
- src/routerClients/AppRouterClient.js
- src/routerClients/PagesRouterClient.js
- src/routerClients/RouterClient.js
- types.d.ts
- allow passing env vairables (config) through handle auth fn
> feat: config in handle auth fn

- src/handlers/auth.js
- src/routerClients/AppRouterClient.js
- src/routerClients/PagesRouterClient.js
- hotfix errors where redirectURL was not being picked up properly
> fix: env variables

- src/config/index.js
- src/routerClients/AppRouterClient.js
- src/routerClients/PagesRouterClient.js
- src/session/getUser.js
- types.d.ts
- enable users to configure scope with `KINDE_SCOPE` in `.env`
- `getUser` now returns phone and username
> feat: KINDE_SCOPE + getUser upgrades

- src/handlers/logout.js
- When supplying a post logout redirect URL to the logout component, this was not consumed and continued to use the environment variable regardless.
- When a relative URL is supplied the site URL will be appended.
> fix: Post logout redirect URL

- readme.md
Fixed an incorrect link that was pointing to Notion and not the docs site.
> Next JS SDK - Update readme.md

- src/handlers/setup.ts
- fix bug with getUserObject 
- change file to TS
> fix: setup get user object + to ts

- src/frontend/KindeBrowserClient.js
- src/session/getUserOrganizations.ts
When Hasura claims are not included in the token the resultant `null` claim causes `getUserOrganizations()` to return `null` due to an exception trying to spread the `null`.
> Fix: coalesce nulls when Hasura claims don't exist 

- types.d.ts
- allow KindeUser type to be used without a specified generic
> types: allow void for generic type

- src/session/getIdToken.js
- fix `getIdToken` bug where `getSessionItem` wasn't being awaited
> fix: get id token (await getSessionItem)

- src/handlers/createOrg.ts
- src/handlers/login.ts
- src/handlers/logout.ts
- src/handlers/register.ts
- src/utils/isPreFetch.test.ts
- src/utils/isPreFetch.ts
Issue: When the auth routes are pre-fetched, this could cause unexpected behaviour. 
Fix: When a prefetch is noticed, ignore them.
> fix: ignore pre-fetch requests on auth routes

- src/authMiddleware/authMiddleware.ts
- src/handlers/login.ts
- src/handlers/logout.ts
- src/handlers/register.ts
- src/utils/isPreFetch.test.ts
- src/utils/isPreFetch.ts
This PR contains some minor fixes for the upcoming 2.5.0 release to improve compatibility with Next 13.
- The bailout for internal Kinde paths (like `login`) has been moved to the very top of the middleware. It has also been expanded to include other paths like `kinde_callback` and `register`. This was the source of a redirect loop in Next 13.
- The prefetch check for `login`, `logout` and `register` links has been reworked to use the `headers()` function instead of directly accessing headers on a `NextRequest` object. In Next 13, the `headers` on a `NextRequest` are an object, but in 14 onwards they're a map. The existing logic treated it like a map and thus caused breakages in Next 13 (`TypeError: e.headers.get is not a function`). Instead, the prefetch check now expects the result of …
> 2.5.0 - Next 13 compatibility

- src/handlers/login.ts
- src/handlers/logout.ts
- src/handlers/register.ts
- src/utils/getHeaders.test.ts
- src/utils/getHeaders.ts
- src/utils/isPreFetch.test.ts
- src/utils/isPreFetch.ts
#257 was necessary to better add compatibility between different Next.js versions in the app router, but inadvertently broke the pages router.
I've introduced a new utility function called `getHeaders` for retrieving headers based on router/next version, with the following flow:
- If a request is passed down (pages router, or app router if we've passed down the request for some reason), return the request headers
- If no request is passed down (app router), dynamically import next/headers and return the awaited headers.
To get error feedback for versions prior to Next 13, where the headers utility did not exist. Next 12 is *very* outdated at this stage regardless.
The `login`, `logout` and `register` route flows have been updated to use this new utility method and pass the results to …
> fix: pages router compat for prefetch header checks

- src/authMiddleware/authMiddleware.ts
Technically this bug has always existed, but is only now being brought to light because the new middleware is protect-all by default.
We use `startsWith` to compare `publicPaths` in the middleware. If a user provided `"/"` as a public path option, it would inadvertently make *all* paths public as all paths start with `"/"`
We have explicit handling for `"/"` public paths now.
Should we be using `startsWith` at all? Let's think of a scenario where a user provides `"/blog"` as a public path. This means that *any* route under `"/blog"` is now considered public. What if there's something a user wants protected under this path, like `"/blog/admin"`? Should we be using explicit comparisons? Allow the user to supply wildcards? Food for thought.
The above could be considered a breaking change …
> fix: improve logic for handling index paths in publicPaths

- src/frontend/KindeBrowserClient.ts
- src/handlers/setup.ts
The `setup` route handler was validating incorrectly and threw raw errors (which Next converts into 500's), even if a user wasn't logged in, which was the source of a constant stream of 500 errors if a user was using the browser client hook.
The `setup` route handler has been reworked to do the following:
- If a user is not logged in (access token or id token does not exist in a session), return a status message but with a 200.
- A user not being logged in is not exactly an error, so a 500 status wouldn't fit here.
- When actual errors occur, return a descriptive status message and error with a 500 status.
- Correctly validate and return refreshed tokens.
`useKindeBrowserClient` has been updated to respect the new messaging and status scheme.
The end result is users will now see 200 …
> fix: rework setup route handler

- src/utils/generateOrganizationObject.ts
generateOrganizationObject will no longer return null if the orgName is not defined
> fix: don't require org name to return org object

- rollup.config.js
- rollupConfig/clientConfig.config.js
I didn't clean my working directory before reviewing #276, so I was inadvertently reviewing the existing and working config - big oops on my behalf.
This pushes typo fixes upstream.
Build log:
> fix missed rollup errors

- package.json
`package.json` was no longer pointing to the correct type declaration file, meaning attempting to import types from `@kinde-oss/kinde-auth-nextjs/types` resulted in errors. This corrects that.
> fix: export the correct type declaration

- src/handlers/callback.ts
`postLoginRedirectURL` was passing parameters to `URL` in the incorrect order - the correct parameter order is `input` (the relative path), then `base`. This was happening in reverse order (we were passing `base` then `relative`). This PR resolves this.
Tested on `next@14.2.24`, `next@15.2.2`
> fix: postLoginRedirectURL within callback

- tsconfig.json
`"module": "NodeNext"` and `"moduleResolution": "NodeNext"` resulted in strange inconsistencies between different machines (and CI actions)
tsconfig has been updated to `ES2022` and `bundler` for maintaining consistency
> fix: change tsconfig for consistency 

- src/authMiddleware/authMiddleware.ts
- src/handlers/setup.ts
- src/utils/cookies/getSplitSerializedCookies.ts
- src/utils/cookies/getStandardCookieOptions.ts
- src/utils/workQueue.ts
When there are multiple client components using the browser client, this can cause multiple calls to `/setup` endpoint.
While middleware and provider could help and solve here, there are cases where setups are not configured like this.  To help these configurations calls to `setup` are now queued and executed one at a time.  This will be prevent double token refresh which can result in unwanted application logouts. 
> feat: queue setup requests to prevent double refresh

- package.json
- pnpm-lock.yaml
Updated TS SDK which includes update to prevent build tool from trying to import expo-secure-store.
fixes: #347
> deps: update kinde TS SDK

- src/handlers/createOrg.ts
- src/handlers/login.ts
- src/handlers/logout.ts
- src/handlers/portal.ts
- src/handlers/register.ts
replaced prefetch skipped 200 with null as returning the 200 causes it to appear for users and prevented further access. 
Replaced in :
- createOrg.ts
- login.ts
- logout.ts
- portal.ts
- register.ts
Testing:
Validating that each of these components still works when the value for the isPreFetch check was rather difficult as there were not any clear reproduction steps that I could find. 
> fix: prefetch skipped error preventing user access

- src/utils/workQueue.ts
setup enqueue and processQueue logs to only appear when isDebugMode true. Make use of `KINDE_DEBUG_MODE` .env variable to allow these console.debug messages to be hidden for users.
Fixes #376 
> fix: setup enqueue and processQueue logs to only appear when isDebugMode true

- src/handlers/setup.ts
Token refresh was failing on subsequent attempts in Pages Router because the session manager wasn't receiving the response object needed to set cookies.
> fix: pages router token refresh by passing both req and res to sessionManager
